'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Sandbox.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Public ReadOnly Property Sandbox_Labels() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sandbox_Labels", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Sandbox_Planarize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sandbox_Planarize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Sandbox_PlateTopology() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sandbox_PlateTopology", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Sandbox_Polygonalize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sandbox_Polygonalize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Sandbox_Topology() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sandbox_Topology", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Sandbox_TopologySorted() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sandbox_TopologySorted", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property Sandbox_Unfold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sandbox_Unfold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property TopologyBrepEdge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TopologyBrepEdge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property TopologyBrepEdgeFilter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TopologyBrepEdgeFilter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property TopologyBrepPoint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TopologyBrepPoint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property TopologyBrepPointFilter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TopologyBrepPointFilter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property TopologyLine() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TopologyLine", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property TopologyLineFilter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TopologyLineFilter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property TopologyMeshEdge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TopologyMeshEdge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property TopologyMeshEdgeFilter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TopologyMeshEdgeFilter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property TopologyMeshPoint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TopologyMeshPoint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property TopologyMeshPointFilter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TopologyMeshPointFilter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property TopologyPolyEdge() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TopologyPolyEdge", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property TopologyPolyEdgeFilter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TopologyPolyEdgeFilter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property TopologyPolyPoint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TopologyPolyPoint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Public ReadOnly Property TopologyPolyPointFilter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TopologyPolyPointFilter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
