// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------


using System.Diagnostics;
using System.Runtime.CompilerServices;
using Microsoft.VisualBasic;

namespace Sandbox.My.Resources
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    [HideModuleName()]
    public static class Resources
    {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("Sandbox.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TopologyBrepEdge
        {
            get
            {
                var obj = ResourceManager.GetObject("TopologyBrepEdge", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TopologyBrepEdgeFilter
        {
            get
            {
                var obj = ResourceManager.GetObject("TopologyBrepEdgeFilter", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TopologyBrepPoint
        {
            get
            {
                var obj = ResourceManager.GetObject("TopologyBrepPoint", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TopologyBrepPointFilter
        {
            get
            {
                var obj = ResourceManager.GetObject("TopologyBrepPointFilter", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TopologyLine
        {
            get
            {
                var obj = ResourceManager.GetObject("TopologyLine", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TopologyLineFilter
        {
            get
            {
                var obj = ResourceManager.GetObject("TopologyLineFilter", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TopologyMeshEdge
        {
            get
            {
                var obj = ResourceManager.GetObject("TopologyMeshEdge", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TopologyMeshEdgeFilter
        {
            get
            {
                var obj = ResourceManager.GetObject("TopologyMeshEdgeFilter", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TopologyMeshPoint
        {
            get
            {
                var obj = ResourceManager.GetObject("TopologyMeshPoint", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TopologyMeshPointFilter
        {
            get
            {
                var obj = ResourceManager.GetObject("TopologyMeshPointFilter", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TopologyPolyEdge
        {
            get
            {
                var obj = ResourceManager.GetObject("TopologyPolyEdge", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TopologyPolyEdgeFilter
        {
            get
            {
                var obj = ResourceManager.GetObject("TopologyPolyEdgeFilter", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TopologyPolyPoint
        {
            get
            {
                var obj = ResourceManager.GetObject("TopologyPolyPoint", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }

        /// <summary>
        /// Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TopologyPolyPointFilter
        {
            get
            {
                var obj = ResourceManager.GetObject("TopologyPolyPointFilter", resourceCulture);
                return (System.Drawing.Bitmap)obj;
            }
        }
    }
}